config/routes.rb
Rails.application.routes.draw do
  
  get 'wishlists/show'
  resources :categories
  devise_for :users
  get 'cards/show'
  resources :products
  resources :shops,only:[:index, :show]

  resources :order_items
  resources :favourite_items
  resources :cards, only:[:show] 
  resources :wishlists, only:[:show]


  root 'shops#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    validates :category, :presence => true, :uniqueness => true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
    has_many :favourite_items
end

app/models/favourite_item.rb
class FavouriteItem < ApplicationRecord
    belongs_to :favourite 
    belongs_to :product 
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal 


    def subtotal
        order_items.collect{|order_item| order_item.valid? ? order_item.unit_price*order_item.quantity : 0}.sum
    end



    private

    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order 
    belongs_to :product 


    before_save :set_unit_price 
    before_save :set_total


    def unit_price
       
            product.price 
       
    end


    def total 
        unit_price * quantity
    end

    private 

    def set_unit_price
         self[:unit_price] = unit_price 
    end

    def set_total 
         self[:total] = total * quantity
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items
    has_many :favourite_items
    belongs_to :category

    def Product.search(search)
        if search 
           where(["title LIKE ?","#{search}%"])

        else
            all
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price, :image_filename, :discription, :category_id)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @products = Product.search(params[:search])
    @order_item = current_order.order_items.new
    @favourite_item = current_favourite.favourite_items.new
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  def show
    @favourite_items = current_favourite.favourite_items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


    def current_order
        if !session[:order_id].nil?
            Order.find(session[:order_id])
        else
            Order.new 
        end
    end

    def current_favourite
        if !session[:favourite_id].nil?
            Favourite.find(session[:favourite_id])
        else
            Favourite.new 
        end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favourite_items_helper.rb
module FavouriteItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/cards/_card.html.erb
<%= link_to "card", cards_show_path%>

app/views/cards/show.html.erb
<h1>Cards Page</h1>

<% @order_items.each do |item| %>
   <h3><%= item.product.title %></h3>
   <h5><%= item.product.price %></h5>
   


   <%= form_for item do |f| %>
       <%= f.hidden_field :product_id, :value => item.product.id %>
       <%= f.number_field :quantity, :value => item.quantity.to_i %>
       <%= f.submit "Update Card" %>

       <%= link_to "Remove Items", order_item_path(item), method: :delete, remote: true%>

   <% end %>

   <h2>Subtotal: <%= item.total %></h2>

<% end %>

<h3>Your current card value has a subtotal of: <%= current_order.subtotal %></h3>

app/views/shops/index.html.erb
<h1> Online Shoping </h1>
<h1>Shop Page</h1>

<p id="notice"><%= notice %></p>

<h1>Products</h1>

<% if current_user %>
    <%= link_to 'sign out', destroy_user_session_path, method: :delete %>
<% else %>
   <%= link_to 'sign up',new_user_registration_path %>

   <%= link_to 'sign in', new_user_session_path %>
<% end %>

<%= form_tag shops_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:serach] %>
  <%= submit_tag "Search" %>
<% end %>


<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Discription</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.discription %></td>
        <td>
           <% if product.image_filename %>
             <p><%= image_tag product.image_filename %></p>
           <% end %>
        </td>
        <td><%= link_to 'Show', shop_path(product) %></td>

        <td>
          <%= form_for @order_item, remote: true do |f|%>
          <%= f.hidden_field :product_id, :value => product.id%>
          <%= f.number_field :quantity, :value => 1, :min => 1%>
          <%= f.submit"Add to Card"%>
     

          <% end %>
        </td>

        <td>
          <%= form_for @favourite_item, remote: true do |f|%>
          <%= f.hidden_field :product_id, :value => product.id%>
          
          <%= f.submit"Add to Wishlist"%>
     

          <% end %>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="Card">
   <%= render 'cards/card' %>

</div>
<%= link_to "Wishlist", wishlists_show_path%>

app/views/shops/show.html.erb
<h1>Shops View</h1>


<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<% if @product.image_filename %>
  <p><%= image_tag @product.image_filename %></p>
<% end %>

<p>
  <strong>Discription:</strong>
  <%= @product.discription %>
</p>

<%= link_to 'Back', root_path %>

app/views/wishlists/show.html.erb
<h1>Wishlists Page</h1>

<% @favourite_items.each do |item| %>
   <p><%= item.product.title %></p>
   <p><%= item.product.price %></p>
   <p><%= image_tag item.product.image_filename %></p>
   


   <%= form_for item do |f| %>
       <%= f.hidden_field :product_id, :value => item.product.id %>
       
       <%= link_to "Remove Items", favourite_item_path(item), method: :delete, remote: true%>

   <% end %>


<% end %>