config/routes.rb
Rails.application.routes.draw do
  
  get 'wishlists/show'
  resources :categories
  devise_for :users
  get 'cards/show'
  resources :products
  resources :shops,only:[:index, :show]

  resources :order_items
  resources :favourite_items
  resources :cards, only:[:show] 
  resources :wishlists, only:[:show]


  root 'shops#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    validates :category, :presence => true, :uniqueness => true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
    has_many :favourite_items
end

app/models/favourite_item.rb
class FavouriteItem < ApplicationRecord
    belongs_to :favourite 
    belongs_to :product 
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal 


    def subtotal
        order_items.collect{|order_item| order_item.valid? ? order_item.unit_price*order_item.quantity : 0}.sum
    end



    private

    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order 
    belongs_to :product 


    before_save :set_unit_price 
    before_save :set_total


    def unit_price
       
            product.price 
       
    end


    def total 
        unit_price * quantity
    end

    private 

    def set_unit_price
         self[:unit_price] = unit_price 
    end

    def set_total 
         self[:total] = total * quantity
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items
    has_many :favourite_items
    belongs_to :category

    def Product.search(search)
        if search 
           where(["title LIKE ?","#{search}%"])

        else
            all
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController



    def create 
       @order = current_order 
       @order_item = @order.order_items.new(order_params)
       @order.save 
       session[:order_id] = @order.id 
    end


    def update 
        @order = current_order 
        @order_item = @order.order_items.find(params[:id])
        @order_item.update(order_params)
        @order_items = current_order.order_items
        redirect_to root_path
    end

    def destroy 
        @order = current_order 
        @order_item = @order.order_items.find(params[:id])
        @order_item.destroy
        @order_items = current_order.order_items
    end


    private

    def order_params
        params.require(:order_item).permit(:product_id, :quantity)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price, :image_filename, :discription, :category_id)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @products = Product.search(params[:search])
    @order_item = current_order.order_items.new
    @favourite_item = current_favourite.favourite_items.new
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  def show
    @favourite_items = current_favourite.favourite_items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


    def current_order
        if !session[:order_id].nil?
            Order.find(session[:order_id])
        else
            Order.new 
        end
    end

    def current_favourite
        if !session[:favourite_id].nil?
            Favourite.find(session[:favourite_id])
        else
            Favourite.new 
        end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favourite_items_helper.rb
module FavouriteItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/order_items/create.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")

app/views/order_items/destroy.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")
$('#card-item').html("<%= escape_javascript(render('cards/cards_item'))%>")

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  

  <div class="field">
    <%= form.label :discription %>
    <%= form.text_area :discription %>
  </div>

  <div class="field">
    <%= form.label :image_filename %>
    <%= form.text_field :image_filename %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.all.map {|c| [c.category, c.id] } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Discription</th>
      <th>Image Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.discription %></td>
        <td> <%= product.image_filename %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Category: <%= @product.category.category %></h1>
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>


<p>
  <strong>Image FileName:</strong>
  <%= @product.image_filename %>
</p>


<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>